project:
  output-dir: ./docs/en

website:
  site-url: "https://brunomontezano.com.br/en"
  title: "Bruno Montezano"
  description: "Psychologist & Data Analyst"
  search: false
  favicon: assets/favicon/favicon.ico
  google-analytics: "G-HL5MJ41HWG"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
    right:
      - href: ../
        text: ðŸ‡§ðŸ‡·
      - href: ../en
        text: ðŸ‡ºðŸ‡¸

lang: en

format:
  html:
    theme:
      - litera
      - assets/css/custom.scss
    page-layout: full
    highlight-style: breeze
    mainfont: Lato
    description-meta: Website of the researcher Bruno Montezano, who works with computational techniques applied to mental health.
    author-meta: Bruno Braga Montezano
    pagetitle: Bruno Montezano
    canonical-url: true
    keywords: [statistics, research, programming, health, phd, masters, psychiatry, psychology]
    toc: true
